const { When, Then } = require('@badeball/cypress-cucumber-preprocessor')
const IndividualsDetailsPage = require('../../../integration/pages/upwPages/individualsDetails/individualsDetailsPage')
const Availability = require('../../../integration/pages/upwPages/placementDetails/availabilityPage')
const Common = require('../../../integration/pages/upwPages/common/common')

When('I see that {string} is Default state on Availability page', () => {
  cy.get(Availability.iWillComeBackLaterRBtn).should('be.checked')
})

When('I select {string} for Mark this section as complete? for Availability', (option) => {
  Availability.selectAvailabilitySectionComplete(option)
})

When('I select the Availability CheckBoxes as follows', (dataTable) => {
  Availability.selectMondayAvailabilityStatus(dataTable.hashes()[0].Monday)
  Availability.selectTuesdayAvailabilityStatus(dataTable.hashes()[1].Tuesday)
  Availability.selectWednesdayAvailabilityStatus(dataTable.hashes()[2].Wednesday)
  Availability.selectThursdayAvailabilityStatus(dataTable.hashes()[1].Thursday)
  Availability.selectFridayAvailabilityStatus(dataTable.hashes()[0].Friday)
  Availability.selectSaturdayAvailabilityStatus(dataTable.hashes()[1].Saturday)
  Availability.selectSundayAvailabilityStatus(dataTable.hashes()[2].Sunday)
})

Then('I enter {string} in the Additional availability information', (details) => {
  Availability.enterAvailabilityInfoDetails(details)
})

Then('I verify that all the Availability related Check Boxes are selected', () => {
  cy.get(Availability.mondayMorningAvlbltyCheckBox).should('not.be.checked')
  cy.get(Availability.mondayAfternoonAvlbltyCheckBox).should('not.be.checked')
  cy.get(Availability.mondayEveningAvlbltyCheckBox).should('not.be.checked')
  cy.get(Availability.tuesdayMorningAvlbltyCheckBox).should('not.be.checked')
  cy.get(Availability.tuesdayAfternoonAvlbltyCheckBox).should('not.be.checked')
  cy.get(Availability.tuesdayEveningAvlbltyCheckBox).should('not.be.checked')
  cy.get(Availability.wednesdayMorningAvlbltyCheckBox).should('not.be.checked')
  cy.get(Availability.wednesdayAfternoonAvlbltyCheckBox).should('not.be.checked')
  cy.get(Availability.wednesdayEveningAvlbltyCheckBox).should('not.be.checked')
  cy.get(Availability.thursdayMorningAvlbltyCheckBox).should('not.be.checked')
  cy.get(Availability.thursdayAfternoonAvlbltyCheckBox).should('not.be.checked')
  cy.get(Availability.thursdayEveningAvlbltyCheckBox).should('not.be.checked')
  cy.get(Availability.fridayMorningAvlbltyCheckBox).should('not.be.checked')
  cy.get(Availability.fridayAfternoonAvlbltyCheckBox).should('not.be.checked')
  cy.get(Availability.fridayEveningAvlbltyCheckBox).should('not.be.checked')
  cy.get(Availability.saturdayMorningAvlbltyCheckBox).should('not.be.checked')
  cy.get(Availability.saturdayAfternoonAvlbltyCheckBox).should('not.be.checked')
  cy.get(Availability.saturdayEveningAvlbltyCheckBox).should('not.be.checked')
  cy.get(Availability.sundayMorningAvlbltyCheckBox).should('not.be.checked')
  cy.get(Availability.sundayAfternoonAvlbltyCheckBox).should('not.be.checked')
  cy.get(Availability.sundayEveningAvlbltyCheckBox).should('not.be.checked')
})

Then('I verify that all the Availability Check Boxes are still selected & deselected as follows', () => {
  cy.get(Availability.mondayMorningAvlbltyCheckBox).should('be.checked')
  cy.get(Availability.mondayAfternoonAvlbltyCheckBox).should('not.be.checked')
  cy.get(Availability.mondayEveningAvlbltyCheckBox).should('not.be.checked')
  cy.get(Availability.tuesdayMorningAvlbltyCheckBox).should('not.be.checked')
  cy.get(Availability.tuesdayAfternoonAvlbltyCheckBox).should('be.checked')
  cy.get(Availability.tuesdayEveningAvlbltyCheckBox).should('not.be.checked')
  cy.get(Availability.wednesdayMorningAvlbltyCheckBox).should('not.be.checked')
  cy.get(Availability.wednesdayAfternoonAvlbltyCheckBox).should('not.be.checked')
  cy.get(Availability.wednesdayEveningAvlbltyCheckBox).should('be.checked')
  cy.get(Availability.thursdayMorningAvlbltyCheckBox).should('not.be.checked')
  cy.get(Availability.thursdayAfternoonAvlbltyCheckBox).should('be.checked')
  cy.get(Availability.thursdayEveningAvlbltyCheckBox).should('not.be.checked')
  cy.get(Availability.fridayMorningAvlbltyCheckBox).should('be.checked')
  cy.get(Availability.fridayAfternoonAvlbltyCheckBox).should('not.be.checked')
  cy.get(Availability.fridayEveningAvlbltyCheckBox).should('not.be.checked')
  cy.get(Availability.saturdayMorningAvlbltyCheckBox).should('not.be.checked')
  cy.get(Availability.saturdayAfternoonAvlbltyCheckBox).should('be.checked')
  cy.get(Availability.saturdayEveningAvlbltyCheckBox).should('not.be.checked')
  cy.get(Availability.sundayMorningAvlbltyCheckBox).should('not.be.checked')
  cy.get(Availability.sundayAfternoonAvlbltyCheckBox).should('not.be.checked')
  cy.get(Availability.sundayEveningAvlbltyCheckBox).should('be.checked')
})

When('I deselect the Availability CheckBoxes and enter the details and Save', () => {
  cy.get(Common.pageHeader).should('contain.text', 'Availability for Community Payback work')
  Availability.selectAvailabilitySectionComplete('Yes')
  IndividualsDetailsPage.clickSaveButton()
})

Then('I see the Availability Summary and Field error messages', (dataTable) => {
  cy.get(Availability.availabiltySummError).should('have.text', dataTable.hashes()[0]['Summary Error Messages'])
  cy.get(Availability.availabiltyFieldError).should('contain.text', dataTable.hashes()[0]['Field Error Messages'])
})

When('I verify the Availability Section as follows', () => {
  cy.get(Availability.mondayMorningAvlbltyCheckBox).should('be.checked')
  cy.get(Availability.mondayAfternoonAvlbltyCheckBox).should('not.be.checked')
  cy.get(Availability.mondayEveningAvlbltyCheckBox).should('not.be.checked')
  cy.get(Availability.tuesdayMorningAvlbltyCheckBox).should('not.be.checked')
  cy.get(Availability.tuesdayAfternoonAvlbltyCheckBox).should('be.checked')
  cy.get(Availability.tuesdayEveningAvlbltyCheckBox).should('not.be.checked')
  cy.get(Availability.wednesdayMorningAvlbltyCheckBox).should('not.be.checked')
  cy.get(Availability.wednesdayAfternoonAvlbltyCheckBox).should('not.be.checked')
  cy.get(Availability.wednesdayEveningAvlbltyCheckBox).should('be.checked')
  cy.get(Availability.thursdayMorningAvlbltyCheckBox).should('not.be.checked')
  cy.get(Availability.thursdayAfternoonAvlbltyCheckBox).should('be.checked')
  cy.get(Availability.thursdayEveningAvlbltyCheckBox).should('not.be.checked')
  cy.get(Availability.fridayMorningAvlbltyCheckBox).should('be.checked')
  cy.get(Availability.fridayAfternoonAvlbltyCheckBox).should('not.be.checked')
  cy.get(Availability.fridayEveningAvlbltyCheckBox).should('not.be.checked')
  cy.get(Availability.saturdayMorningAvlbltyCheckBox).should('not.be.checked')
  cy.get(Availability.saturdayAfternoonAvlbltyCheckBox).should('be.checked')
  cy.get(Availability.saturdayEveningAvlbltyCheckBox).should('not.be.checked')
  cy.get(Availability.sundayMorningAvlbltyCheckBox).should('not.be.checked')
  cy.get(Availability.sundayAfternoonAvlbltyCheckBox).should('not.be.checked')
  cy.get(Availability.sundayEveningAvlbltyCheckBox).should('be.checked')
})

Then('I verify the text {string} in the Additional availability information', (details) => {
  cy.get(Availability.availabilityInfoTextBox).should('contain', details)
})
